# Generated by Django 4.2.23 on 2025-08-30 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('area_name', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'area',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('quest_name', models.CharField(blank=True, max_length=15, null=True)),
                ('boss', models.IntegerField(blank=True, null=True)),
                ('min0', models.BooleanField(blank=True, db_column='0分', null=True)),
                ('min3', models.BooleanField(blank=True, db_column='3分', null=True)),
                ('min10', models.BooleanField(blank=True, db_column='10分', null=True)),
                ('min30', models.BooleanField(blank=True, db_column='30分', null=True)),
                ('hr1', models.BooleanField(blank=True, db_column='1小時', null=True)),
                ('hr2', models.BooleanField(blank=True, db_column='2小時', null=True)),
                ('hr4', models.BooleanField(blank=True, db_column='4小時', null=True)),
                ('hr8', models.BooleanField(blank=True, db_column='8小時', null=True)),
                ('hr16', models.BooleanField(blank=True, db_column='16小時', null=True)),
                ('day1', models.BooleanField(blank=True, db_column='1天', null=True)),
                ('day3', models.BooleanField(blank=True, db_column='3天', null=True)),
                ('m1', models.IntegerField(blank=True, db_column='M1', null=True)),
                ('m2', models.IntegerField(blank=True, db_column='M2', null=True)),
                ('m3', models.IntegerField(blank=True, db_column='M3', null=True)),
                ('iron', models.IntegerField(blank=True, db_column='鐵幣', null=True)),
                ('bronze', models.IntegerField(blank=True, db_column='銅幣', null=True)),
                ('gold', models.IntegerField(blank=True, db_column='金幣', null=True)),
                ('platinum', models.IntegerField(blank=True, db_column='白金幣', null=True)),
                ('memory', models.IntegerField(blank=True, db_column='記憶的碎片', null=True)),
                ('light', models.IntegerField(blank=True, db_column='生命的碎片', null=True)),
            ],
            options={
                'db_table': 'quest',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('region_name', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'region',
                'managed': True,
            },
        ),
    ]
