# Generated by Django 4.2.23 on 2025-08-30 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quest',
            options={'managed': True},
        ),
    ]
