# Generated by Django 4.2.23 on 2025-08-30 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_quest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='silver',
            field=models.IntegerField(blank=True, db_column='銀幣', null=True),
        ),
        migrations.AddField(
            model_name='quest',
            name='soul',
            field=models.IntegerField(blank=True, db_column='靈魂的碎片', null=True),
        ),
        migrations.AddField(
            model_name='quest',
            name='time',
            field=models.IntegerField(blank=True, db_column='時間的碎片', null=True),
        ),
        migrations.AddField(
            model_name='quest',
            name='unlight',
            field=models.IntegerField(blank=True, db_column='死亡的碎片', null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='boss',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
