# Generated by Django 4.2.23 on 2025-08-30 05:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_quest_region_quest_silver_quest_soul_quest_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='boss',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='bronze',
            field=models.IntegerField(blank=True, db_column='銅幣', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='quest',
            name='day1',
            field=models.BooleanField(blank=True, db_column='1天', default=True, null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='day3',
            field=models.BooleanField(blank=True, db_column='3天', default=True, null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='gold',
            field=models.IntegerField(blank=True, db_column='金幣', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='quest',
            name='hr1',
            field=models.BooleanField(blank=True, db_column='1小時', default=True, null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='hr16',
            field=models.BooleanField(blank=True, db_column='16小時', default=True, null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='hr2',
            field=models.BooleanField(blank=True, db_column='2小時', default=True, null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='hr4',
            field=models.BooleanField(blank=True, db_column='4小時', default=True, null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='hr8',
            field=models.BooleanField(blank=True, db_column='8小時', default=True, null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quest',
            name='iron',
            field=models.IntegerField(blank=True, db_column='鐵幣', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='quest',
            name='light',
            field=models.IntegerField(blank=True, db_column='生命的碎片', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='quest',
            name='m1',
            field=models.IntegerField(blank=True, db_column='M1', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='quest',
            name='m2',
            field=models.IntegerField(blank=True, db_column='M2', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='quest',
            name='m3',
            field=models.IntegerField(blank=True, db_column='M3', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='quest',
            name='memory',
            field=models.IntegerField(blank=True, db_column='記憶的碎片', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='quest',
            name='min0',
            field=models.BooleanField(blank=True, db_column='0分', default=True, null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='min10',
            field=models.BooleanField(blank=True, db_column='10分', default=True, null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='min3',
            field=models.BooleanField(blank=True, db_column='3分', default=True, null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='min30',
            field=models.BooleanField(blank=True, db_column='30分', default=True, null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='platinum',
            field=models.IntegerField(blank=True, db_column='白金幣', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='quest',
            name='silver',
            field=models.IntegerField(blank=True, db_column='銀幣', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='quest',
            name='soul',
            field=models.IntegerField(blank=True, db_column='靈魂的碎片', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='quest',
            name='time',
            field=models.IntegerField(blank=True, db_column='時間的碎片', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='quest',
            name='unlight',
            field=models.IntegerField(blank=True, db_column='死亡的碎片', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
