# Generated by Django 4.2.23 on 2025-08-31 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_quest_region_alter_quest_boss_alter_quest_bronze_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='region',
            field=models.ForeignKey(blank=True, 
                                    db_column='region_id', 
                                    null=True, 
                                    on_delete=django.db.models.deletion.DO_NOTHING, 
                                    to='app.region'),
        ),
        migrations.AddField(
            model_name='quest',
            name='treasure',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
