# Generated by Django 4.2.23 on 2025-09-02 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_quest_region_quest_treasure'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitrhPlace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('eng_name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'bitrhplace',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('eng_name', models.CharField(blank=True, max_length=20, null=True)),
                ('level', models.PositiveSmallIntegerField(blank=True, db_column='level', null=True)),
            ],
            options={
                'db_table': 'monster',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='quest',
            name='quest_name',
            field=models.CharField(blank=True, db_column='quest_name', max_length=15, null=True),
        ),
        migrations.RenameField(
            model_name='quest',
            old_name='quest_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='quest',
            name='boss',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='quest',
            name='bronze',
            field=models.PositiveSmallIntegerField(blank=True, db_column='銅幣', null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='day1',
            field=models.BooleanField(blank=True, db_column='1天', default=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='day3',
            field=models.BooleanField(blank=True, db_column='3天', default=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='gold',
            field=models.PositiveSmallIntegerField(blank=True, db_column='金幣', null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='hr1',
            field=models.BooleanField(blank=True, db_column='1小時', default=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='hr16',
            field=models.BooleanField(blank=True, db_column='16小時', default=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='hr2',
            field=models.BooleanField(blank=True, db_column='2小時', default=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='hr4',
            field=models.BooleanField(blank=True, db_column='4小時', default=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='hr8',
            field=models.BooleanField(blank=True, db_column='8小時', default=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='iron',
            field=models.PositiveSmallIntegerField(blank=True, db_column='鐵幣', null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='light',
            field=models.PositiveSmallIntegerField(blank=True, db_column='生命的碎片', null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='m1',
            field=models.PositiveSmallIntegerField(blank=True, db_column='M1', null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='m2',
            field=models.PositiveSmallIntegerField(blank=True, db_column='M2', null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='m3',
            field=models.PositiveSmallIntegerField(blank=True, db_column='M3', null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='memory',
            field=models.PositiveSmallIntegerField(blank=True, db_column='記憶的碎片', null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='min0',
            field=models.BooleanField(blank=True, db_column='0分', default=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='min10',
            field=models.BooleanField(blank=True, db_column='10分', default=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='min3',
            field=models.BooleanField(blank=True, db_column='3分', default=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='min30',
            field=models.BooleanField(blank=True, db_column='30分', default=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='platinum',
            field=models.PositiveSmallIntegerField(blank=True, db_column='白金幣', null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='silver',
            field=models.PositiveSmallIntegerField(blank=True, db_column='銀幣', null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='soul',
            field=models.PositiveSmallIntegerField(blank=True, db_column='靈魂的碎片', null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='time',
            field=models.PositiveSmallIntegerField(blank=True, db_column='時間的碎片', null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='treasure',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='quest',
            name='unlight',
            field=models.PositiveSmallIntegerField(blank=True, db_column='死亡的碎片', null=True),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('eng_name', models.CharField(blank=True, max_length=15, null=True)),
                ('jp_name', models.CharField(blank=True, max_length=15, null=True)),
                ('birth_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('birth_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('blood_type', models.CharField(blank=True, max_length=3, null=True)),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('birth_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.bitrhplace')),
            ],
            options={
                'db_table': 'character',
                'managed': True,
            },
        ),
    ]
