# Generated by Django 4.2.23 on 2025-09-04 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_bitrhplace_monster_alter_quest_quest_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BitrhPlace',
            new_name='BirthPlace',
        ),
        migrations.AddField(
            model_name='character',
            name='cv',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='hobby',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='title',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='ATK',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='DEF',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='HP',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='cost',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='birth_place',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='app.birthplace',  # ← 這裡從 app.bitrhplace 改成 app.birthplace
            ),
        ),
        migrations.AlterField(
            model_name='character',
            name='jp_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='region',
            field=models.ForeignKey(blank=True, db_column='region_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.region'),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ex', models.BooleanField(blank=True, default=False)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('eng_name', models.CharField(blank=True, max_length=10, null=True)),
                ('phase', models.CharField(choices=[('ATK', 'Attack'), ('DEF', 'Defense'), ('MOV', 'Move')], max_length=15)),
                ('base_skill', models.ForeignKey(blank=True, db_column='base_skill_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.skill')),
            ],
            options={
                'db_table': 'skill',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CharacterCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('card_type', models.CharField(blank=True, max_length=3, null=True)),
                ('level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cost', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('HP', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ATK', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('DEF', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('event_gun', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('event_sword', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('event_defense', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('event_special', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('event_move', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('event_chance', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('event_curse', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('memory', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('time', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('soul', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('light', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('unlight', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('chaosium', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('character', models.ForeignKey(blank=True, db_column='character_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.character')),
            ],
            options={
                'db_table': 'character_card',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='character',
            name='exskill1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exskill1_character', to='app.skill'),
        ),
        migrations.AddField(
            model_name='character',
            name='exskill2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exskill2_character', to='app.skill'),
        ),
        migrations.AddField(
            model_name='character',
            name='exskill3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exskill3_character', to='app.skill'),
        ),
        migrations.AddField(
            model_name='character',
            name='exskill4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exskill4_character', to='app.skill'),
        ),
        migrations.AddField(
            model_name='character',
            name='skill1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill1_character', to='app.skill'),
        ),
        migrations.AddField(
            model_name='character',
            name='skill2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill2_character', to='app.skill'),
        ),
        migrations.AddField(
            model_name='character',
            name='skill3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill3_character', to='app.skill'),
        ),
        migrations.AddField(
            model_name='character',
            name='skill4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill4_character', to='app.skill'),
        ),
    ]
