# Generated by Django 4.2.23 on 2025-09-05 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_bitrhplace_birthplace_character_cv_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='birthplace',
            table='birthplace',
        ),
    ]
