# Generated by Django 4.2.23 on 2025-09-05 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_area_options_alter_region_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='area_name',
            field=models.CharField(blank=True, db_column='area_name', max_length=10, null=True),
        ),
        migrations.RenameField(
            model_name='area',
            old_name='area_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='region',
            name='region_name',
            field=models.CharField(blank=True, db_column='region_name', max_length=10, null=True),
        ),
        migrations.RenameField(
            model_name='region',
            old_name='region_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='monster',
            name='family',
            field=models.ForeignKey(blank=True, db_column='base_monster_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.monster'),
        ),
        migrations.AddField(
            model_name='region',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.area'),
        ),
        migrations.AlterField(
            model_name='area',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='region',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]