# Generated by Django 4.2.23 on 2025-09-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_area_area_name_rename_area_name_area_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='eng_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
