# Generated by Django 4.2.23 on 2025-09-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_monster_eng_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='monsters/'),
        ),
    ]
