# Generated by Django 4.2.23 on 2025-09-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_monster_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactercard',
            name='crazy',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='charactercard',
            name='vanity',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='charactercard',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
