# Generated by Django 4.2.23 on 2025-09-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_charactercard_crazy_charactercard_vanity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='description',
            new_name='description_jp',
        ),
        migrations.AddField(
            model_name='character',
            name='description_cn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
