# Generated by Django 4.2.23 on 2025-09-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_description_character_description_jp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='card_requirements',
            field=models.JSONField(blank=True, default=dict, help_text="需求卡片/武器數量，例如 {'gun': 2} / {'sword':1, 'gun':1}"),
        ),
        migrations.AddField(
            model_name='skill',
            name='distance_mask',
            field=models.PositiveSmallIntegerField(default=0, help_text='bitmask: 近=1, 中=2, 遠=4，可 OR 組合'),
        ),
    ]
