# Generated by Django 4.2.23 on 2025-09-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_skill_card_requirements_skill_distance_mask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='distance_mask',
        ),
        migrations.AddField(
            model_name='skill',
            name='far',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='mid',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='near',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
