# Generated by Django 4.2.23 on 2025-09-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_skill_distance_mask_skill_far_skill_mid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='card_requirements',
            field=models.JSONField(blank=True, default=dict, help_text='需求卡片/武器數量，例如 {"gun": 2} / {\'sword\':1, \'gun\':1}'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='eng_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
