# Generated by Django 4.2.23 on 2025-09-12 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_skill_card_requirements_alter_skill_eng_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrenchMonth',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fr_name', models.CharField(blank=True, max_length=11, null=True)),
                ('cn_name', models.CharField(blank=True, max_length=1, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='french_month/')),
            ],
            options={
                'db_table': 'french_month',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='skill',
            name='card_requirements',
            field=models.JSONField(blank=True, default=dict, help_text='需求卡片/武器數量，例如 {"gun": 2} / {"sword": 1, "gun": 1}'),
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('solar_m', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('solar_d', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fr_d', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fr_name', models.CharField(blank=True, max_length=15, null=True)),
                ('en_name', models.CharField(blank=True, max_length=19, null=True)),
                ('cn_name', models.CharField(blank=True, max_length=6, null=True)),
                ('fr_m', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.frenchmonth')),
            ],
            options={
                'db_table': 'calendar',
                'managed': True,
            },
        ),
    ]
