# Generated by Django 4.2.23 on 2025-09-12 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_frenchmonth_alter_skill_card_requirements_calendar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='birth_month',
        ),
        migrations.AlterField(
            model_name='character',
            name='birth_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.calendar'),
        ),
    ]
