# Generated by Django 4.2.23 on 2025-09-14 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_character_birth_month_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frenchmonth',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='QuestStage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stage', models.PositiveSmallIntegerField()),
                ('position', models.CharField(choices=[('left', 'left'), ('middle', 'middle'), ('right', 'right')], max_length=6)),
                ('gem', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('text_reward', models.CharField(blank=True, max_length=15, null=True)),
                ('characard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.charactercard')),
                ('monster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.monster')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='app.quest')),
            ],
            options={
                'db_table': 'quest_stage',
                'managed': True,
            },
        ),
    ]
