# Generated by Django 4.2.23 on 2025-09-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_frenchmonth_options_queststage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queststage',
            name='position',
            field=models.CharField(choices=[('L', 'left'), ('M', 'middle'), ('R', 'right')], max_length=1),
        ),
    ]
