# Generated by Django 4.2.23 on 2025-09-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_quest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queststage',
            name='gem',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='queststage',
            name='position',
            field=models.CharField(choices=[('L', 'L'), ('M', 'M'), ('R', 'R')], max_length=1),
        ),
    ]
