# Generated by Django 4.2.23 on 2025-09-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_queststage_gem_alter_queststage_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queststage',
            name='text_reward',
            field=models.CharField(default='', max_length=15),
        ),
    ]
