# Generated by Django 4.2.23 on 2025-09-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_queststage_text_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='goal',
            field=models.PositiveSmallIntegerField(blank=True, default=1),
        ),
    ]
