# Generated by Django 4.2.23 on 2025-10-10 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_quest_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regions', to='app.area'),
        ),
    ]
