# Generated by Django 4.2.23 on 2025-10-11 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_region_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(blank=True, db_column='area_name', default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='birthplace',
            name='eng_name',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='birthplace',
            name='name',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='cn_name',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='en_name',
            field=models.CharField(blank=True, default='', max_length=19),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='fr_d',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='fr_m',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.frenchmonth'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='fr_name',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='solar_d',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='solar_m',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='blood_type',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='character',
            name='cv',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='character',
            name='description_cn',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='description_jp',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='eng_name',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='character',
            name='height',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='hobby',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='jp_name',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='title',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='character',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='charactercard',
            name='ATK',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='charactercard',
            name='DEF',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='charactercard',
            name='HP',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='charactercard',
            name='card_type',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='charactercard',
            name='cost',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='charactercard',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='monster',
            name='ATK',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='monster',
            name='DEF',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='monster',
            name='HP',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='monster',
            name='cost',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='monster',
            name='eng_name',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='monster',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, db_column='level', default=0),
        ),
        migrations.AlterField(
            model_name='monster',
            name='name',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='quest',
            name='bronze',
            field=models.PositiveSmallIntegerField(blank=True, db_column='銅幣', default=0),
        ),
        migrations.AlterField(
            model_name='quest',
            name='gold',
            field=models.PositiveSmallIntegerField(blank=True, db_column='金幣', default=0),
        ),
        migrations.AlterField(
            model_name='quest',
            name='iron',
            field=models.PositiveSmallIntegerField(blank=True, db_column='鐵幣', default=0),
        ),
        migrations.AlterField(
            model_name='quest',
            name='light',
            field=models.PositiveSmallIntegerField(blank=True, db_column='生命的碎片', default=0),
        ),
        migrations.AlterField(
            model_name='quest',
            name='m1',
            field=models.PositiveSmallIntegerField(blank=True, db_column='M1', default=0),
        ),
        migrations.AlterField(
            model_name='quest',
            name='m2',
            field=models.PositiveSmallIntegerField(blank=True, db_column='M2', default=0),
        ),
        migrations.AlterField(
            model_name='quest',
            name='m3',
            field=models.PositiveSmallIntegerField(blank=True, db_column='M3', default=0),
        ),
        migrations.AlterField(
            model_name='quest',
            name='memory',
            field=models.PositiveSmallIntegerField(blank=True, db_column='記憶的碎片', default=0),
        ),
        migrations.AlterField(
            model_name='quest',
            name='name',
            field=models.CharField(blank=True, db_column='quest_name', default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='quest',
            name='platinum',
            field=models.PositiveSmallIntegerField(blank=True, db_column='白金幣', default=0),
        ),
        migrations.AlterField(
            model_name='quest',
            name='silver',
            field=models.PositiveSmallIntegerField(blank=True, db_column='銀幣', default=0),
        ),
        migrations.AlterField(
            model_name='quest',
            name='soul',
            field=models.PositiveSmallIntegerField(blank=True, db_column='靈魂的碎片', default=0),
        ),
        migrations.AlterField(
            model_name='quest',
            name='time',
            field=models.PositiveSmallIntegerField(blank=True, db_column='時間的碎片', default=0),
        ),
        migrations.AlterField(
            model_name='quest',
            name='unlight',
            field=models.PositiveSmallIntegerField(blank=True, db_column='死亡的碎片', default=0),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(blank=True, db_column='region_name', default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='skill',
            name='eng_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='skill',
            name='phase',
            field=models.CharField(choices=[('ATK', 'Attack'), ('DEF', 'Defense'), ('MOV', 'Move')], default='', max_length=15),
        ),
    ]
